// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonMsg.proto

package PersonMsgPackage;

public final class PersonMsgClassName {
  private PersonMsgClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID（必需）
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID（必需）
     * </pre>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated .PersonMsgPackage.Person.Friend friends = 4;
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend> 
        getFriendsList();
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    PersonMsgPackage.PersonMsgClassName.Person.Friend getFriends(int index);
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    int getFriendsCount();
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    java.util.List<? extends PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder> 
        getFriendsOrBuilderList();
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder getFriendsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PersonMsgPackage.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                friends_ = new java.util.ArrayList<PersonMsgPackage.PersonMsgClassName.Person.Friend>();
                mutable_bitField0_ |= 0x00000008;
              }
              friends_.add(input.readMessage(PersonMsgPackage.PersonMsgClassName.Person.Friend.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          friends_ = java.util.Collections.unmodifiableList(friends_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonMsgPackage.PersonMsgClassName.Person.class, PersonMsgPackage.PersonMsgClassName.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public interface FriendOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required int32 age = 2;
      /**
       * <code>required int32 age = 2;</code>
       */
      boolean hasAge();
      /**
       * <code>required int32 age = 2;</code>
       */
      int getAge();
    }
    /**
     * Protobuf type {@code PersonMsgPackage.Person.Friend}
     */
    public static final class Friend extends
        com.google.protobuf.GeneratedMessage
        implements FriendOrBuilder {
      // Use Friend.newBuilder() to construct.
      private Friend(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Friend(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Friend defaultInstance;
      public static Friend getDefaultInstance() {
        return defaultInstance;
      }

      public Friend getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Friend(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                age_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_Friend_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_Friend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMsgPackage.PersonMsgClassName.Person.Friend.class, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder.class);
      }

      public static com.google.protobuf.Parser<Friend> PARSER =
          new com.google.protobuf.AbstractParser<Friend>() {
        public Friend parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Friend(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Friend> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required int32 age = 2;
      public static final int AGE_FIELD_NUMBER = 2;
      private int age_;
      /**
       * <code>required int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }

      private void initFields() {
        name_ = "";
        age_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAge()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, age_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, age_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PersonMsgPackage.PersonMsgClassName.Person.Friend parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(PersonMsgPackage.PersonMsgClassName.Person.Friend prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PersonMsgPackage.Person.Friend}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_Friend_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_Friend_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PersonMsgPackage.PersonMsgClassName.Person.Friend.class, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder.class);
        }

        // Construct using PersonMsgPackage.PersonMsgClassName.Person.Friend.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          age_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_Friend_descriptor;
        }

        public PersonMsgPackage.PersonMsgClassName.Person.Friend getDefaultInstanceForType() {
          return PersonMsgPackage.PersonMsgClassName.Person.Friend.getDefaultInstance();
        }

        public PersonMsgPackage.PersonMsgClassName.Person.Friend build() {
          PersonMsgPackage.PersonMsgClassName.Person.Friend result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public PersonMsgPackage.PersonMsgClassName.Person.Friend buildPartial() {
          PersonMsgPackage.PersonMsgClassName.Person.Friend result = new PersonMsgPackage.PersonMsgClassName.Person.Friend(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.age_ = age_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PersonMsgPackage.PersonMsgClassName.Person.Friend) {
            return mergeFrom((PersonMsgPackage.PersonMsgClassName.Person.Friend)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PersonMsgPackage.PersonMsgClassName.Person.Friend other) {
          if (other == PersonMsgPackage.PersonMsgClassName.Person.Friend.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasAge()) {
            setAge(other.getAge());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasAge()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PersonMsgPackage.PersonMsgClassName.Person.Friend parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PersonMsgPackage.PersonMsgClassName.Person.Friend) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required int32 age = 2;
        private int age_ ;
        /**
         * <code>required int32 age = 2;</code>
         */
        public boolean hasAge() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 age = 2;</code>
         */
        public int getAge() {
          return age_;
        }
        /**
         * <code>required int32 age = 2;</code>
         */
        public Builder setAge(int value) {
          bitField0_ |= 0x00000002;
          age_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 age = 2;</code>
         */
        public Builder clearAge() {
          bitField0_ = (bitField0_ & ~0x00000002);
          age_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:PersonMsgPackage.Person.Friend)
      }

      static {
        defaultInstance = new Friend(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:PersonMsgPackage.Person.Friend)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID（必需）
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID（必需）
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     *
     * <pre>
     * 姓名（必需）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     *
     * <pre>
     * email（可选）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .PersonMsgPackage.Person.Friend friends = 4;
    public static final int FRIENDS_FIELD_NUMBER = 4;
    private java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend> friends_;
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    public java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend> getFriendsList() {
      return friends_;
    }
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    public java.util.List<? extends PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder> 
        getFriendsOrBuilderList() {
      return friends_;
    }
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    public PersonMsgPackage.PersonMsgClassName.Person.Friend getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
     *
     * <pre>
     * 朋友（集合）
     * </pre>
     */
    public PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder getFriendsOrBuilder(
        int index) {
      return friends_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      friends_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFriendsCount(); i++) {
        if (!getFriends(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < friends_.size(); i++) {
        output.writeMessage(4, friends_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < friends_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, friends_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsgPackage.PersonMsgClassName.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonMsgPackage.PersonMsgClassName.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonMsgPackage.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonMsgPackage.PersonMsgClassName.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMsgPackage.PersonMsgClassName.Person.class, PersonMsgPackage.PersonMsgClassName.Person.Builder.class);
      }

      // Construct using PersonMsgPackage.PersonMsgClassName.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFriendsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          friendsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonMsgPackage.PersonMsgClassName.internal_static_PersonMsgPackage_Person_descriptor;
      }

      public PersonMsgPackage.PersonMsgClassName.Person getDefaultInstanceForType() {
        return PersonMsgPackage.PersonMsgClassName.Person.getDefaultInstance();
      }

      public PersonMsgPackage.PersonMsgClassName.Person build() {
        PersonMsgPackage.PersonMsgClassName.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonMsgPackage.PersonMsgClassName.Person buildPartial() {
        PersonMsgPackage.PersonMsgClassName.Person result = new PersonMsgPackage.PersonMsgClassName.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (friendsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            friends_ = java.util.Collections.unmodifiableList(friends_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.friends_ = friends_;
        } else {
          result.friends_ = friendsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonMsgPackage.PersonMsgClassName.Person) {
          return mergeFrom((PersonMsgPackage.PersonMsgClassName.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonMsgPackage.PersonMsgClassName.Person other) {
        if (other == PersonMsgPackage.PersonMsgClassName.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (friendsBuilder_ == null) {
          if (!other.friends_.isEmpty()) {
            if (friends_.isEmpty()) {
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFriendsIsMutable();
              friends_.addAll(other.friends_);
            }
            onChanged();
          }
        } else {
          if (!other.friends_.isEmpty()) {
            if (friendsBuilder_.isEmpty()) {
              friendsBuilder_.dispose();
              friendsBuilder_ = null;
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000008);
              friendsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFriendsFieldBuilder() : null;
            } else {
              friendsBuilder_.addAllMessages(other.friends_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getFriendsCount(); i++) {
          if (!getFriends(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonMsgPackage.PersonMsgClassName.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonMsgPackage.PersonMsgClassName.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID（必需）
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID（必需）
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID（必需）
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID（必需）
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       *
       * <pre>
       * 姓名（必需）
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       *
       * <pre>
       * email（可选）
       * </pre>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated .PersonMsgPackage.Person.Friend friends = 4;
      private java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend> friends_ =
        java.util.Collections.emptyList();
      private void ensureFriendsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          friends_ = new java.util.ArrayList<PersonMsgPackage.PersonMsgClassName.Person.Friend>(friends_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PersonMsgPackage.PersonMsgClassName.Person.Friend, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder, PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder> friendsBuilder_;

      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend> getFriendsList() {
        if (friendsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friends_);
        } else {
          return friendsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public int getFriendsCount() {
        if (friendsBuilder_ == null) {
          return friends_.size();
        } else {
          return friendsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public PersonMsgPackage.PersonMsgClassName.Person.Friend getFriends(int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);
        } else {
          return friendsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder setFriends(
          int index, PersonMsgPackage.PersonMsgClassName.Person.Friend value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.set(index, value);
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder setFriends(
          int index, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder addFriends(PersonMsgPackage.PersonMsgClassName.Person.Friend value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder addFriends(
          int index, PersonMsgPackage.PersonMsgClassName.Person.Friend value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(index, value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder addFriends(
          PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder addFriends(
          int index, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder addAllFriends(
          java.lang.Iterable<? extends PersonMsgPackage.PersonMsgClassName.Person.Friend> values) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          super.addAll(values, friends_);
          onChanged();
        } else {
          friendsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder clearFriends() {
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          friendsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public Builder removeFriends(int index) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.remove(index);
          onChanged();
        } else {
          friendsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder getFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder getFriendsOrBuilder(
          int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);  } else {
          return friendsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public java.util.List<? extends PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder> 
           getFriendsOrBuilderList() {
        if (friendsBuilder_ != null) {
          return friendsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friends_);
        }
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder addFriendsBuilder() {
        return getFriendsFieldBuilder().addBuilder(
            PersonMsgPackage.PersonMsgClassName.Person.Friend.getDefaultInstance());
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder addFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().addBuilder(
            index, PersonMsgPackage.PersonMsgClassName.Person.Friend.getDefaultInstance());
      }
      /**
       * <code>repeated .PersonMsgPackage.Person.Friend friends = 4;</code>
       *
       * <pre>
       * 朋友（集合）
       * </pre>
       */
      public java.util.List<PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder> 
           getFriendsBuilderList() {
        return getFriendsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PersonMsgPackage.PersonMsgClassName.Person.Friend, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder, PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder> 
          getFriendsFieldBuilder() {
        if (friendsBuilder_ == null) {
          friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PersonMsgPackage.PersonMsgClassName.Person.Friend, PersonMsgPackage.PersonMsgClassName.Person.Friend.Builder, PersonMsgPackage.PersonMsgClassName.Person.FriendOrBuilder>(
                  friends_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          friends_ = null;
        }
        return friendsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PersonMsgPackage.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PersonMsgPackage.Person)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonMsgPackage_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonMsgPackage_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonMsgPackage_Person_Friend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PersonMsgPackage_Person_Friend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PersonMsg.proto\022\020PersonMsgPackage\"\210\001\n\006" +
      "Person\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\r\n\005emai" +
      "l\030\003 \001(\t\0220\n\007friends\030\004 \003(\0132\037.PersonMsgPack" +
      "age.Person.Friend\032#\n\006Friend\022\014\n\004name\030\001 \002(" +
      "\t\022\013\n\003age\030\002 \002(\005B\024B\022PersonMsgClassName"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PersonMsgPackage_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PersonMsgPackage_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonMsgPackage_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "Friends", });
          internal_static_PersonMsgPackage_Person_Friend_descriptor =
            internal_static_PersonMsgPackage_Person_descriptor.getNestedTypes().get(0);
          internal_static_PersonMsgPackage_Person_Friend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PersonMsgPackage_Person_Friend_descriptor,
              new java.lang.String[] { "Name", "Age", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
